-- Profile Step 1: extend pharmacists/pharmacies and add audit table
-- Run after 04_multitenancy.sql

ALTER TABLE pharmacists
  ADD COLUMN IF NOT EXISTS title VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(30) NULL,
  ADD COLUMN IF NOT EXISTS license_no VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS license_expiry DATE NULL,
  ADD COLUMN IF NOT EXISTS accreditation_body VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS timezone VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS locale VARCHAR(16) NULL,
  ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS city VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS state VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS country VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(255) NULL;

ALTER TABLE pharmacies
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(200) NULL,
  ADD COLUMN IF NOT EXISTS city VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS state VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS country VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS timezone VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS locale VARCHAR(16) NULL;

CREATE TABLE IF NOT EXISTS pharmacist_profile_audit (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  pharmacist_id INT NOT NULL,
  changed_fields JSON NOT NULL,
  changed_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_pharmacist (pharmacist_id),
  CONSTRAINT fk_audit_pharmacist FOREIGN KEY (pharmacist_id) REFERENCES pharmacists(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
