-- 07_purchases_extensions.sql
-- Extend purchase_orders and purchase_order_items for richer header and line-item fields

ALTER TABLE purchase_orders
  ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'YER',
  ADD COLUMN IF NOT EXISTS exchange_rate DECIMAL(12,6) DEFAULT 1,
  ADD COLUMN IF NOT EXISTS supplier_reference VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS expected_date DATE NULL,
  ADD COLUMN IF NOT EXISTS payment_terms VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS shipping_terms VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS amount_received DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_remaining DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS expiry_date DATE NULL;

ALTER TABLE purchase_order_items
  MODIFY COLUMN medicine_id INT NULL,
  ADD COLUMN IF NOT EXISTS item_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS supplier_item_code VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS barcode VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS batch_no VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS expiry_date DATE NULL,
  ADD COLUMN IF NOT EXISTS unit VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS discount_percent DECIMAL(6,2) NULL,
  ADD COLUMN IF NOT EXISTS discount_value DECIMAL(12,2) NULL,
  ADD COLUMN IF NOT EXISTS free_qty INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_bonus TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS taxes JSON NULL,
  ADD COLUMN IF NOT EXISTS extra_charges_share DECIMAL(12,2) NULL,
  ADD COLUMN IF NOT EXISTS generic_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS form VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS strength VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS location VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS notes TEXT NULL,
  ADD COLUMN IF NOT EXISTS min_stock DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_stock DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wholesale_price DECIMAL(12,4) NULL,
  ADD COLUMN IF NOT EXISTS retail_price DECIMAL(12,4) NULL,
  ADD COLUMN IF NOT EXISTS carton_price DECIMAL(12,4) NULL,
  ADD COLUMN IF NOT EXISTS blister_price DECIMAL(12,4) NULL,
  ADD COLUMN IF NOT EXISTS tablet_price DECIMAL(12,4) NULL,
  ADD COLUMN IF NOT EXISTS packs_per_carton INT NULL,
  ADD COLUMN IF NOT EXISTS blisters_per_pack INT NULL,
  ADD COLUMN IF NOT EXISTS tablets_per_blister INT NULL;

ALTER TABLE medicines
  ADD COLUMN IF NOT EXISTS packs_per_carton INT NULL,
  ADD COLUMN IF NOT EXISTS blisters_per_pack INT NULL,
  ADD COLUMN IF NOT EXISTS tablets_per_blister INT NULL;