ALTER TABLE purchase_order_items
  ADD COLUMN IF NOT EXISTS category VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS wholesale_price DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS retail_price DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carton_price DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS blister_price DECIMAL(12,4) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tablet_price DECIMAL(12,6) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS packs_per_carton INT NULL,
  ADD COLUMN IF NOT EXISTS blisters_per_pack INT NULL,
  ADD COLUMN IF NOT EXISTS tablets_per_blister INT NULL,
  ADD COLUMN IF NOT EXISTS received_qty DECIMAL(10,2) DEFAULT 0,
  MODIFY COLUMN unit_price DECIMAL(12,4) NOT NULL,
  MODIFY COLUMN line_total DECIMAL(12,2) NOT NULL;